export const SERVER_CONFIGURATION_CATEGORY_ORDER = [
  "基础与服务器",
  "世界与事件",
  "时间与成长",
  "玩家生存",
  "帕鲁生态",
  "战斗与死亡",
  "掉落与资源",
  "建筑与据点",
  "公会",
  "PvP",
  "网络与访问",
  "接口与日志",
  "性能与同步",
  "语音与隐私",
  "高级与兼容",
] as const;

export type ServerConfigurationCategory = (typeof SERVER_CONFIGURATION_CATEGORY_ORDER)[number];

export type ServerConfigurationDefinition = {
  key: string;
  label: string;
  help: string;
  category: ServerConfigurationCategory;
  unit?: string;
  dangerous?: boolean;
  min?: number;
  max?: number;
  step?: number;
};

/**
 * Palworld Dedicated Server v1.0.0 / Steam build 24088465 的
 * DefaultPalWorldSettings.ini 元数据。顺序与官方默认文件保持一致。
 *
 * 数值边界只在官方文档、游戏哨兵值或控制 API 既有校验有依据时提供；
 * 未公开边界的内部参数不应由前端擅自夹断。
 */
export const SERVER_CONFIGURATION_DEFINITIONS = [
  { key: "Difficulty", label: "预设难度", help: "自定义服务器通常保持 None，由下方倍率决定实际难度。", category: "基础与服务器" },
  { key: "RandomizerType", label: "帕鲁随机化模式", help: "None 不随机，Region 按区域随机，All 完全随机。", category: "世界与事件", dangerous: true },
  { key: "RandomizerSeed", label: "随机化种子", help: "仅在启用帕鲁随机化时使用；相同种子用于复现分布。", category: "世界与事件" },
  { key: "bIsRandomizerPalLevelRandom", label: "帕鲁等级完全随机", help: "关闭时只在区域适配等级内随机。", category: "世界与事件", dangerous: true },
  { key: "DayTimeSpeedRate", label: "白天流逝速度", help: "白天时间推进倍率。", category: "时间与成长", unit: "倍", min: 0.1, max: 20, step: 0.1 },
  { key: "NightTimeSpeedRate", label: "夜晚流逝速度", help: "夜晚时间推进倍率。", category: "时间与成长", unit: "倍", min: 0.1, max: 20, step: 0.1 },
  { key: "ExpRate", label: "经验获取倍率", help: "玩家与帕鲁获得经验的倍率。", category: "时间与成长", unit: "倍", min: 0.1, max: 20, step: 0.1 },
  { key: "PalCaptureRate", label: "帕鲁捕获倍率", help: "影响帕鲁球的捕获成功率。", category: "帕鲁生态", unit: "倍", min: 0.1, max: 20, step: 0.1 },
  { key: "PalSpawnNumRate", label: "帕鲁生成数量倍率", help: "提高会显著增加服务器计算与同步负载。", category: "帕鲁生态", unit: "倍", min: 0.1, max: 20, step: 0.1, dangerous: true },
  { key: "PalDamageRateAttack", label: "帕鲁造成伤害倍率", help: "帕鲁攻击造成的伤害倍率。", category: "战斗与死亡", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "PalDamageRateDefense", label: "帕鲁承受伤害倍率", help: "帕鲁受到伤害的倍率。", category: "战斗与死亡", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "PlayerDamageRateAttack", label: "玩家造成伤害倍率", help: "玩家攻击造成的伤害倍率。", category: "战斗与死亡", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "PlayerDamageRateDefense", label: "玩家承受伤害倍率", help: "玩家受到伤害的倍率。", category: "战斗与死亡", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "PlayerStomachDecreaceRate", label: "玩家饱食度消耗倍率", help: "数值越高，玩家越容易饥饿。", category: "玩家生存", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "PlayerStaminaDecreaceRate", label: "玩家耐力消耗倍率", help: "数值越高，玩家耐力消耗越快。", category: "玩家生存", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "PlayerAutoHPRegeneRate", label: "玩家生命自然恢复倍率", help: "玩家非睡眠状态的生命恢复倍率。", category: "玩家生存", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "PlayerAutoHpRegeneRateInSleep", label: "玩家睡眠恢复倍率", help: "玩家睡眠时的生命恢复倍率。", category: "玩家生存", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "PalStomachDecreaceRate", label: "帕鲁饱食度消耗倍率", help: "数值越高，帕鲁越容易饥饿。", category: "帕鲁生态", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "PalStaminaDecreaceRate", label: "帕鲁耐力消耗倍率", help: "数值越高，帕鲁耐力消耗越快。", category: "帕鲁生态", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "PalAutoHPRegeneRate", label: "帕鲁生命自然恢复倍率", help: "帕鲁在外活动时的生命恢复倍率。", category: "帕鲁生态", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "PalAutoHpRegeneRateInSleep", label: "帕鲁盒恢复倍率", help: "帕鲁在帕鲁盒内休息时的生命恢复倍率。", category: "帕鲁生态", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "BuildObjectHpRate", label: "建筑生命值倍率", help: "建筑与设施最大生命值倍率。", category: "建筑与据点", unit: "倍", min: 0.1, max: 20, step: 0.1 },
  { key: "BuildObjectDamageRate", label: "建筑承受伤害倍率", help: "建筑受到攻击时的伤害倍率。", category: "建筑与据点", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "BuildObjectDeteriorationDamageRate", label: "建筑劣化倍率", help: "据点外建筑随时间损耗的倍率；0 通常用于关闭劣化。", category: "建筑与据点", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "CollectionDropRate", label: "采集掉落倍率", help: "采集资源获得数量的倍率。", category: "掉落与资源", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "CollectionObjectHpRate", label: "采集物生命值倍率", help: "矿石、树木等采集对象耐久倍率。", category: "掉落与资源", unit: "倍", min: 0.1, max: 20, step: 0.1 },
  { key: "CollectionObjectRespawnSpeedRate", label: "采集物重生间隔倍率", help: "控制采集对象的重生间隔倍率。", category: "掉落与资源", unit: "倍", min: 0.1, max: 20, step: 0.1 },
  { key: "EnemyDropItemRate", label: "敌人掉落倍率", help: "敌人掉落物品数量的倍率。", category: "掉落与资源", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "DeathPenalty", label: "死亡惩罚", help: "None 无掉落；Item 掉落非装备物品；ItemAndEquipment 掉落物品和装备；All 还会掉落队伍帕鲁。", category: "战斗与死亡", dangerous: true },
  { key: "bEnablePlayerToPlayerDamage", label: "玩家间伤害", help: "允许玩家对其他玩家造成伤害，是 PvP 的组成开关。", category: "PvP", dangerous: true },
  { key: "bEnableFriendlyFire", label: "友军伤害", help: "允许同阵营成员互相造成伤害。", category: "PvP", dangerous: true },
  { key: "bEnableInvaderEnemy", label: "启用袭击事件", help: "允许据点遭遇敌人袭击。", category: "世界与事件" },
  { key: "bActiveUNKO", label: "启用 UNKO 机制", help: "官方未公开说明的保留开关，建议保持默认。", category: "高级与兼容", dangerous: true },
  { key: "bEnableAimAssistPad", label: "手柄瞄准辅助", help: "允许使用手柄的客户端启用瞄准辅助。", category: "玩家生存" },
  { key: "bEnableAimAssistKeyboard", label: "键鼠瞄准辅助", help: "允许使用键鼠的客户端启用瞄准辅助。", category: "玩家生存" },
  { key: "DropItemMaxNum", label: "世界掉落物上限", help: "世界中可保留的普通掉落物数量；提高会增加负载。", category: "性能与同步", unit: "个", min: 0, max: 100000, step: 1, dangerous: true },
  { key: "PhysicsActiveDropItemMaxNum", label: "物理模拟掉落物上限", help: "可启用物理行为的掉落物数量；-1 表示使用游戏默认策略。", category: "性能与同步", unit: "个", min: -1, max: 100000, step: 1, dangerous: true },
  { key: "DropItemMaxNum_UNKO", label: "UNKO 掉落物上限", help: "UNKO 类掉落物的世界数量上限。", category: "性能与同步", unit: "个", min: 0, max: 100000, step: 1, dangerous: true },
  { key: "BaseCampMaxNum", label: "全服据点总上限", help: "整个服务器可存在的据点总数；提高会增加负载。", category: "建筑与据点", unit: "个", min: 1, step: 1, dangerous: true },
  { key: "BaseCampWorkerMaxNum", label: "每据点工作帕鲁上限", help: "官方上限为 50；提高会增加服务器负载。", category: "建筑与据点", unit: "只", min: 1, max: 50, step: 1, dangerous: true },
  { key: "DropItemAliveMaxHours", label: "掉落物存活时间", help: "无人拾取的世界掉落物最长保留时间。", category: "掉落与资源", unit: "小时", min: 0, max: 168, step: 0.1 },
  { key: "bAutoResetGuildNoOnlinePlayers", label: "自动清理长期离线公会", help: "到期后会删除离线公会的建筑与据点帕鲁，启用前必须确认策略。", category: "公会", dangerous: true },
  { key: "AutoResetGuildTimeNoOnlinePlayers", label: "离线公会清理等待时间", help: "仅在启用自动清理长期离线公会时生效。", category: "公会", unit: "小时", min: 0, step: 1, dangerous: true },
  { key: "GuildPlayerMaxNum", label: "每公会玩家上限", help: "一个公会可容纳的最大玩家数。", category: "公会", unit: "人", min: 1, max: 100, step: 1 },
  { key: "BaseCampMaxNumInGuild", label: "每公会据点上限", help: "官方文档给出的最大值为 10；提高会增加负载。", category: "公会", unit: "个", min: 1, max: 10, step: 1, dangerous: true },
  { key: "PalEggDefaultHatchingTime", label: "巨大帕鲁蛋孵化时间", help: "巨大帕鲁蛋的基础孵化小时数，其他蛋会按比例计算。", category: "帕鲁生态", unit: "小时", min: 0, max: 240, step: 0.1 },
  { key: "WorkSpeedRate", label: "工作速度倍率", help: "玩家与据点生产相关工作速度倍率。", category: "时间与成长", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "AutoSaveSpan", label: "自动保存间隔", help: "游戏自动保存世界数据的时间间隔。", category: "性能与同步", unit: "秒", min: 1, max: 3600, step: 1 },
  { key: "bIsMultiplay", label: "多人游戏内部标记", help: "官方未公开说明的内部标记，专用服务器建议保持默认。", category: "高级与兼容", dangerous: true },
  { key: "bIsPvP", label: "启用 PvP 模式", help: "开启服务器 PvP 规则；通常还需配合玩家伤害和跨公会防御。", category: "PvP", dangerous: true },
  { key: "bHardcore", label: "硬核模式", help: "玩家死亡后无法正常重生，可能造成不可逆体验变化。", category: "战斗与死亡", dangerous: true },
  { key: "bPalLost", label: "死亡永久失去帕鲁", help: "死亡时永久失去帕鲁，启用前应先建立可验证备份。", category: "战斗与死亡", dangerous: true },
  { key: "bCharacterRecreateInHardcore", label: "硬核死亡后允许重建角色", help: "控制硬核模式死亡后是否可重新创建角色。", category: "战斗与死亡", dangerous: true },
  { key: "bCanPickupOtherGuildDeathPenaltyDrop", label: "允许拾取其他公会死亡掉落", help: "允许玩家拿走其他公会成员的死亡惩罚掉落物。", category: "PvP", dangerous: true },
  { key: "bEnableNonLoginPenalty", label: "启用离线惩罚", help: "官方未公开完整规则，修改可能影响长期离线玩家与公会。", category: "高级与兼容", dangerous: true },
  { key: "bEnableFastTravel", label: "启用快速旅行", help: "允许玩家使用快速旅行点。", category: "世界与事件" },
  { key: "bEnableFastTravelOnlyBaseCamp", label: "仅允许据点间快速旅行", help: "启用后，快速旅行只允许在据点之间进行。", category: "PvP" },
  { key: "bIsStartLocationSelectByMap", label: "允许地图选择出生点", help: "允许新角色从地图选择开始位置。", category: "玩家生存" },
  { key: "bExistPlayerAfterLogout", label: "登出后角色留在世界", help: "玩家登出后角色仍在原地睡眠，可被世界规则影响。", category: "PvP", dangerous: true },
  { key: "bEnableDefenseOtherGuildPlayer", label: "据点防御其他公会玩家", help: "允许据点帕鲁攻击进入范围的敌对公会玩家。", category: "PvP", dangerous: true },
  { key: "bInvisibleOtherGuildBaseCampAreaFX", label: "隐藏其他公会据点范围", help: "控制其他公会据点范围效果是否不可见。", category: "PvP" },
  { key: "bBuildAreaLimit", label: "限制重要地点附近建造", help: "禁止在传送点、出生点等重要区域附近建造。", category: "建筑与据点" },
  { key: "ItemWeightRate", label: "物品重量倍率", help: "所有物品重量的倍率。", category: "掉落与资源", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "CoopPlayerMaxNum", label: "合作队伍人数上限", help: "官方未单独说明其专服行为，通常保持默认 4。", category: "高级与兼容", unit: "人", min: 1, max: 32, step: 1 },
  { key: "ServerPlayerMaxNum", label: "服务器玩家上限", help: "可同时加入服务器的最大玩家数。", category: "基础与服务器", unit: "人", min: 1, max: 128, step: 1, dangerous: true },
  { key: "ServerName", label: "服务器名称", help: "显示在服务器列表和游戏内的名称。", category: "基础与服务器" },
  { key: "ServerDescription", label: "服务器描述", help: "服务器列表中显示的说明文字。", category: "基础与服务器" },
  { key: "AdminPassword", label: "管理员密码", help: "用于取得管理员权限及官方 REST API 基本认证，必须妥善保管。", category: "网络与访问", dangerous: true },
  { key: "ServerPassword", label: "加入服务器密码", help: "玩家加入服务器时需要输入的密码；留空表示不设密码。", category: "网络与访问", dangerous: true },
  { key: "bAllowClientMod", label: "允许客户端模组", help: "允许启用了模组的客户端加入，可能扩大兼容性与作弊风险。", category: "网络与访问", dangerous: true },
  { key: "PublicPort", label: "社区服务器外部端口", help: "仅用于社区服务器公告，不会改变实际游戏监听端口。", category: "网络与访问", min: 1, max: 65535, step: 1, unit: "端口", dangerous: true },
  { key: "PublicIP", label: "社区服务器外部 IP", help: "仅在自动探测外网地址失败时手动指定。", category: "网络与访问", dangerous: true },
  { key: "RCONEnabled", label: "启用 RCON", help: "开启远程控制协议；必须限制监听范围并设置强管理员密码。", category: "接口与日志", dangerous: true },
  { key: "RCONPort", label: "RCON 端口", help: "RCON 服务监听端口。", category: "接口与日志", min: 1, max: 65535, step: 1, unit: "端口", dangerous: true },
  { key: "Region", label: "服务器区域", help: "社区服务器区域标识；通常留空交由游戏判断。", category: "网络与访问" },
  { key: "bUseAuth", label: "启用平台认证", help: "控制平台身份认证；关闭会降低访问安全性。", category: "网络与访问", dangerous: true },
  { key: "BanListURL", label: "官方封禁列表地址", help: "游戏定期获取的封禁列表 URL；改为非可信地址会引入供应链风险。", category: "网络与访问", dangerous: true },
  { key: "RESTAPIEnabled", label: "启用官方 REST API", help: "启用 Palworld 官方管理 API；不要直接暴露到公网。", category: "接口与日志", dangerous: true },
  { key: "RESTAPIPort", label: "官方 REST API 端口", help: "官方 REST API 的监听端口。", category: "接口与日志", min: 1, max: 65535, step: 1, unit: "端口", dangerous: true },
  { key: "bShowPlayerList", label: "ESC 菜单显示玩家列表", help: "允许客户端在 ESC 菜单查看玩家列表。", category: "语音与隐私" },
  { key: "ChatPostLimitPerMinute", label: "每分钟聊天上限", help: "单个玩家每分钟允许发送的聊天消息数量。", category: "接口与日志", unit: "条/分钟", min: 0, step: 1 },
  { key: "CrossplayPlatforms", label: "允许连接的平台", help: "平台列表，例如 (Steam,Xbox,PS5,Mac)。", category: "网络与访问", dangerous: true },
  { key: "bIsUseBackupSaveData", label: "启用游戏原生备份", help: "让游戏轮转保存世界备份；关闭会失去一层恢复保障。", category: "性能与同步", dangerous: true },
  { key: "LogFormatType", label: "日志格式", help: "支持 Text 或 Json。", category: "接口与日志" },
  { key: "bIsShowJoinLeftMessage", label: "显示玩家加入/离开消息", help: "在游戏内显示玩家上线与离线提示。", category: "接口与日志" },
  { key: "SupplyDropSpan", label: "陨石与补给投放间隔", help: "陨石和补给投放事件的基础间隔。", category: "世界与事件", unit: "分钟", min: 1, step: 1 },
  { key: "EnablePredatorBossPal", label: "启用捕食者头目帕鲁", help: "控制世界中捕食者头目帕鲁事件。", category: "世界与事件" },
  { key: "MaxBuildingLimitNum", label: "每玩家建筑数量上限", help: "0 表示不限制；设置上限可控制大型据点负载。", category: "建筑与据点", unit: "个", min: 0, step: 1, dangerous: true },
  { key: "ServerReplicatePawnCullDistance", label: "帕鲁同步距离", help: "玩家周围同步帕鲁的距离；官方范围为 5000 至 15000 厘米。", category: "性能与同步", unit: "厘米", min: 5000, max: 15000, step: 100, dangerous: true },
  { key: "bAllowGlobalPalboxExport", label: "允许导出到全局帕鲁盒", help: "允许玩家把帕鲁保存到跨世界全局帕鲁盒。", category: "帕鲁生态", dangerous: true },
  { key: "bAllowGlobalPalboxImport", label: "允许从全局帕鲁盒导入", help: "允许从其他世界导入帕鲁，可能影响经济与进度公平。", category: "帕鲁生态", dangerous: true },
  { key: "EquipmentDurabilityDamageRate", label: "装备耐久损耗倍率", help: "装备使用和受击时的耐久度损耗倍率。", category: "玩家生存", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "ItemContainerForceMarkDirtyInterval", label: "容器强制重同步间隔", help: "容器界面打开时强制重新同步的频率。", category: "性能与同步", unit: "秒", min: 0.1, step: 0.1, dangerous: true },
  { key: "PlayerDataPalStorageUpdateCheckTickInterval", label: "玩家帕鲁存储检查间隔", help: "官方未公开完整语义的同步检查间隔；过低会增加负载。", category: "性能与同步", unit: "秒", min: 0.1, step: 0.1, dangerous: true },
  { key: "ItemCorruptionMultiplier", label: "食物腐败速度倍率", help: "食物等带腐败计时物品的变质速度倍率。", category: "掉落与资源", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "MonsterFarmActionSpeedRate", label: "牧场生产速度倍率", help: "帕鲁在牧场产出物品的动作速度倍率。", category: "帕鲁生态", unit: "倍", min: 0, max: 20, step: 0.1 },
  { key: "DenyTechnologyList", label: "禁用科技列表", help: "填写科技 ID 列表，用于禁止指定科技；应通过科技目录选择。", category: "时间与成长", dangerous: true },
  { key: "GuildRejoinCooldownMinutes", label: "公会重新加入冷却", help: "玩家离开公会后再次加入公会需等待的时间。", category: "公会", unit: "分钟", min: 0, step: 1 },
  { key: "AutoTransferMasterCheckIntervalSeconds", label: "会长自动转让检查间隔", help: "官方文档未公开的公会维护参数，控制会长转让检查频率。", category: "高级与兼容", unit: "秒", min: 1, step: 1, dangerous: true },
  { key: "AutoTransferMasterThresholdDays", label: "会长自动转让离线阈值", help: "公会会长离线达到该天数后可能触发自动转让。", category: "公会", unit: "天", min: 0, step: 1, dangerous: true },
  { key: "MaxGuildsPerFrame", label: "每帧处理公会数量", help: "内部性能参数；提高可能造成单帧卡顿，降低会延长维护任务。", category: "高级与兼容", unit: "个/帧", min: 1, step: 1, dangerous: true },
  { key: "BlockRespawnTime", label: "基础重生等待时间", help: "玩家死亡后的基础重生冷却。", category: "PvP", unit: "秒", min: 0, step: 0.1 },
  { key: "RespawnPenaltyDurationThreshold", label: "重生惩罚重置阈值", help: "玩家存活达到该时长后，连续死亡惩罚恢复到基础值；0 表示不设置额外时长。", category: "PvP", unit: "秒", min: 0, step: 1 },
  { key: "RespawnPenaltyTimeScale", label: "连续死亡重生倍率", help: "在阈值时间内再次死亡时，重生冷却的倍率。", category: "PvP", unit: "倍", min: 0, step: 0.1 },
  { key: "bDisplayPvPItemNumOnWorldMap_BaseCamp", label: "地图显示据点 PvP 物品数", help: "在世界地图上显示各据点持有的 PvP 专用物品数量。", category: "PvP" },
  { key: "bDisplayPvPItemNumOnWorldMap_Player", label: "地图显示玩家 PvP 物品数", help: "在世界地图显示玩家位置及其 PvP 专用物品数量。", category: "PvP", dangerous: true },
  { key: "AdditionalDropItemWhenPlayerKillingInPvPMode", label: "PvP 击杀额外掉落物", help: "PvP 击杀玩家时额外掉落的物品 ID。", category: "PvP", dangerous: true },
  { key: "AdditionalDropItemNumWhenPlayerKillingInPvPMode", label: "PvP 击杀额外掉落数量", help: "PvP 击杀额外掉落物的数量。", category: "PvP", unit: "个", min: 1, step: 1, dangerous: true },
  { key: "bAdditionalDropItemWhenPlayerKillingInPvPMode", label: "启用 PvP 击杀额外掉落", help: "开启后，PvP 击杀会按物品 ID 和数量生成奖励。", category: "PvP", dangerous: true },
  { key: "bEnableVoiceChat", label: "启用游戏内语音", help: "允许玩家使用游戏内语音，需考虑隐私、带宽和管理策略。", category: "语音与隐私", dangerous: true },
  { key: "VoiceChatMaxVolumeDistance", label: "语音满音量距离", help: "在该距离内语音不衰减。", category: "语音与隐私", unit: "厘米", min: 0, step: 100 },
  { key: "VoiceChatZeroVolumeDistance", label: "语音静音距离", help: "达到该距离后语音音量降为零，应不小于满音量距离。", category: "语音与隐私", unit: "厘米", min: 0, step: 100 },
  { key: "bAllowEnhanceStat_Health", label: "允许强化生命值", help: "允许玩家把属性点分配到生命值。", category: "时间与成长" },
  { key: "bAllowEnhanceStat_Attack", label: "允许强化攻击力", help: "允许玩家把属性点分配到攻击力。", category: "时间与成长" },
  { key: "bAllowEnhanceStat_Stamina", label: "允许强化耐力", help: "允许玩家把属性点分配到耐力。", category: "时间与成长" },
  { key: "bAllowEnhanceStat_Weight", label: "允许强化负重", help: "允许玩家把属性点分配到负重。", category: "时间与成长" },
  { key: "bAllowEnhanceStat_WorkSpeed", label: "允许强化工作速度", help: "允许玩家把属性点分配到工作速度。", category: "时间与成长" },
  { key: "bEnableBuildingPlayerUIdDisplay", label: "建筑显示创建者玩家 ID", help: "在建筑信息中显示创建者玩家 ID，启用前应评估隐私影响。", category: "语音与隐私", dangerous: true },
  { key: "BuildingNameDisplayCacheTTLSeconds", label: "建筑名称显示缓存时间", help: "官方未公开完整语义的建筑名称缓存存活时间。", category: "高级与兼容", unit: "秒", min: 0, step: 1, dangerous: true },
] as const satisfies readonly ServerConfigurationDefinition[];

export const SERVER_CONFIGURATION_DEFINITION_BY_KEY: ReadonlyMap<string, ServerConfigurationDefinition> =
  new Map(SERVER_CONFIGURATION_DEFINITIONS.map((definition) => [definition.key, definition]));
